
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: srvcz-api-providers-canary
spec:
  selector:
    matchLabels:
      app: providers-service
      role: providers
  replicas: 3
  template:
    metadata:
      name: srvcz-api-deployment
      labels:
        app: providers-service
        role: providers
        env: canary
    spec:
      containers:
      - name: providers
        image: gcr.io/srvc-marketplace/providers-service:master.9
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGODB_URL
          #- name: API_URL
           # valueFrom:
           #   secretKeyRef:
            #    name: lesvault
           #     key: api_url_staging
          - name: NODE_ENV
            value: production
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8190
        #args: ['--env="HOST_IP=$(HOST_IP)"','--env="API_URL=$(API_URL)"','--env="MONGODB_URL=$(MONGODB_URL)"']
        ports:
        - name: providers
          containerPort: 8190