apiVersion: v1
kind: Service
metadata:
  name: srvcz-web-admin-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  selector:
    app: web-admin-service
    role: web-admin
